export const ADD_METHOD_INITIATED = "ADD_METHOD_INITIATED";
export const ADD_METHOD_SUCCESS = "ADD_METHOD_SUCCESS";
export const ADD_METHOD_ERROR = "ADD_METHOD_ERROR";

export const GET_METHODS_INITIATED = "GET_METHODS_INITIATED";
export const GET_METHODS_SUCCESS = "GET_METHODS_SUCCESS";
export const GET_METHODS_ERROR = "GET_METHODS_ERROR";

export const DELETE_METHODS_INITIATED = "DELETE_METHODS_INITIATED";
export const DELETE_METHODS_SUCCESS = "DELETE_METHODS_SUCCESS";
export const DELETE_METHODS_ERROR = "DELETE_METHODS_ERROR";

export const UPDATE_METHODS_INITIATED = "UPDATE_METHODS_INITIATED";
export const UPDATE_METHODS_SUCCESS = "UPDATE_METHODS_SUCCESS";
export const UPDATE_METHODS_ERROR = "UPDATE_METHODS_ERROR";