export const ADD_PAYMENT_INITIATED = "ADD_PAYMENT_INITIATED";
export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_ERROR = "ADD_PAYMENT_ERROR";

export const GET_PAYMENTS_INITIATED = "GET_PAYMENTS_INITIATED";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_ERROR = "GET_PAYMENTS_ERROR";

export const DELETE_PAYMENTS_INITIATED = "DELETE_PAYMENTS_INITIATED";
export const DELETE_PAYMENTS_SUCCESS = "DELETE_PAYMENTS_SUCCESS";
export const DELETE_PAYMENTS_ERROR = "DELETE_PAYMENTS_ERROR";